# Multiclass -  Neural Network

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from sklearn.preprocessing import LabelEncoder

## DataSet

In [5]:
path = "./dataset-01/Iris/iris.csv"
dataset = pd.read_csv(path)

print(dataset.columns.values)

['Id' 'SepalLengthCm' 'SepalWidthCm' 'PetalLengthCm' 'PetalWidthCm'
 'Species']


In [6]:
#X = dataset[['SepalLengthCm','SepalWidthCm','PetalLengthCm','PetalWidthCm']]
X = dataset.copy()
X = X.drop(columns = ['Id','Species']) # inplace=True
#X.drop('Id', inplace=True, axis=1)
y = dataset['Species']

print(y[:5])
print(X[:5])

0    Iris-setosa
1    Iris-setosa
2    Iris-setosa
3    Iris-setosa
4    Iris-setosa
Name: Species, dtype: object
   SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0            5.1           3.5            1.4           0.2
1            4.9           3.0            1.4           0.2
2            4.7           3.2            1.3           0.2
3            4.6           3.1            1.5           0.2
4            5.0           3.6            1.4           0.2


In [7]:
y.unique() # Unique values in y (possible classes)

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [8]:
class_mapping = {'Iris-setosa': 0, 'Iris-versicolor': 1, 'Iris-virginica': 2}
y = dataset['Species'].map(class_mapping)
print(y)

0      0
1      0
2      0
3      0
4      0
      ..
145    2
146    2
147    2
148    2
149    2
Name: Species, Length: 150, dtype: int64


### Splitting in training and testing

In [9]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(
    X, 
    y,
    test_size = 0.3,
    random_state=10
)
print(len(dataset))
print(len(x_train))
print(len(x_test))


150
105
45


In [11]:
print(x_train.shape)
print(y_train.shape)
print(y_train[:10])

(105, 4)
(105,)
32     0
52     1
70     1
121    2
144    2
68     1
109    2
81     1
78     1
51     1
Name: Species, dtype: int64


## Tensorflow Model

### Creating the Model

In [13]:
model = Sequential(
    [
        Dense(4, activation='relu'),
        Dense(8, activation='relu'),
        Dense(3, activation='softmax')
    ]
)

In [27]:
model.compile(
    loss = tf.keras.losses.SparseCategoricalCrossentropy(),
    optimizer=tf.keras.optimizers.Adam(0.001),
    metrics='accuracy'
)

In [28]:
model.fit(x_train,y_train, epochs=100, validation_data=(x_test, y_test))

Epoch 1/100
4/4 [==============================] - 0s 57ms/step - loss: 0.0675 - accuracy: 0.9810 - val_loss: 0.0397 - val_accuracy: 1.0000
Epoch 2/100
4/4 [==============================] - 0s 26ms/step - loss: 0.0649 - accuracy: 0.9714 - val_loss: 0.0402 - val_accuracy: 1.0000
Epoch 3/100
4/4 [==============================] - 0s 24ms/step - loss: 0.0653 - accuracy: 0.9810 - val_loss: 0.0413 - val_accuracy: 0.9778
Epoch 4/100
4/4 [==============================] - 0s 30ms/step - loss: 0.0662 - accuracy: 0.9810 - val_loss: 0.0419 - val_accuracy: 0.9778
Epoch 5/100
4/4 [==============================] - 0s 23ms/step - loss: 0.0667 - accuracy: 0.9810 - val_loss: 0.0417 - val_accuracy: 0.9778
Epoch 6/100
4/4 [==============================] - 0s 21ms/step - loss: 0.0661 - accuracy: 0.9810 - val_loss: 0.0413 - val_accuracy: 0.9778
Epoch 7/100
4/4 [==============================] - 0s 26ms/step - loss: 0.0657 - accuracy: 0.9810 - val_loss: 0.0407 - val_accuracy: 1.0000
Epoch 8/100
4/4 [===

In [30]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_3 (Dense)             (None, 4)                 20        
                                                                 
 dense_4 (Dense)             (None, 8)                 40        
                                                                 
 dense_5 (Dense)             (None, 3)                 27        
                                                                 
Total params: 87
Trainable params: 87
Non-trainable params: 0
_________________________________________________________________


### Predictions

In [32]:
test_loss, test_accuracy = model.evaluate(x_test, y_test)
print(test_loss:.4f)
print(test_accuracy)

In [36]:
predictions = model.predict(x_test)
print("Predictions = \n", predictions[:5])

2/2 [==============================] - 0s 4ms/step
Predictions = 
 [[6.9191812e-11 9.7830975e-01 2.1690223e-02]
 [4.5390347e-24 2.4932638e-02 9.7506738e-01]
 [9.9442190e-01 5.4789861e-03 9.9108162e-05]
 [4.0088228e-11 9.7474968e-01 2.5250373e-02]
 [9.9442190e-01 5.4789861e-03 9.9108162e-05]]


In [38]:
y_pred = []

for i in range(len(predictions)):
    y_pred.append(np.argmax(predictions[i]))
    print(f"{predictions[i]}, class: {np.argmax(predictions[i])}")

[6.9191812e-11 9.7830975e-01 2.1690223e-02], class: 1
[4.5390347e-24 2.4932638e-02 9.7506738e-01], class: 2
[9.944219e-01 5.478986e-03 9.910816e-05], class: 0
[4.0088228e-11 9.7474968e-01 2.5250373e-02], class: 1
[9.944219e-01 5.478986e-03 9.910816e-05], class: 0
[5.1494103e-06 9.9767929e-01 2.3156409e-03], class: 1
[2.5273788e-16 6.0654110e-01 3.9345884e-01], class: 1
[2.0114607e-05 9.9726069e-01 2.7191816e-03], class: 1
[9.944219e-01 5.478986e-03 9.910816e-05], class: 0
[2.6250916e-11 9.7177774e-01 2.8222281e-02], class: 1
[6.1140443e-13 9.2402232e-01 7.5977705e-02], class: 1
[2.2950768e-24 2.1308988e-02 9.7869098e-01], class: 2
[3.6834072e-10 9.8623002e-01 1.3770017e-02], class: 1
[9.944219e-01 5.478986e-03 9.910816e-05], class: 0
[9.944219e-01 5.478986e-03 9.910816e-05], class: 0
[1.2425216e-25 1.1435302e-02 9.8856467e-01], class: 2
[4.5255005e-11 9.7567743e-01 2.4322538e-02], class: 1
[9.944219e-01 5.478986e-03 9.910816e-05], class: 0
[9.944219e-01 5.478986e-03 9.910816e-05], clas

In [42]:
acc = np.mean(y_pred == y_test.to_numpy())
print(f"Test set score: {acc:.2f}%")

Test set score: 1.00%


In [1]:
from sklearn.metrics import confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt

##If using one hot-encodiing
y_pred_ = np.argmax(predctions, axis=1)
y_test = np.argmax(y_test, axis=1)

cm = confusion_matrix(y_test, y_pred)
sns.heatmap(cm, annot=True, fmt="d")
plt.xlabel('Predicted')
plt.ylabel('True')
plt.show()

NameError: name 'np' is not defined