### Building a neural network

In [11]:
import tensorflow as tf
from tensorflow.keras import layers, Sequential
import numpy as np

In [12]:
x = np.array([[350.0, 45.0]])

layer1 = layers.Dense(units = 3, activation = 'sigmoid')

a1 = layer1(x)
print(a1)


layer2 = layers.Dense(units = 1, activation = 'sigmoid')
a2 = layer2(a1)
print(a2)

tf.Tensor([[0. 1. 0.]], shape=(1, 3), dtype=float32)
tf.Tensor([[0.37611207]], shape=(1, 1), dtype=float32)


In [13]:
# create a dataset

X = np.array([[400.0, 28.0],
             [475.0, 35.0], 
             [470.0, 36.0],
             [500.0, 30.0],
             [250.0, 25.0],
             [330.0, 38.0],
             [350.0, 55.0],
             [350.0, 40.0],
             [350.0, 45.0]
             ])

y = np.array([1,1,1,0,0,1,0,1,1])

In [14]:
layer1 = layers.Dense(units = 3, activation = 'sigmoid')
layer2 = layers.Dense(units = 1, activation = 'sigmoid')

model = Sequential ([layer1, layer2])

In [15]:
# model = Sequential([
#     layers.Dense(unites=3, activation = 'sigmoid'),
#     layers.Dense(unites=1, activation = 'sigmoid')
# ])


In [32]:
from tensorflow.keras.losses import BinaryCrossentropy
model.compile(loss = BinaryCrossentropy())

In [33]:
model.fit(X, y, epochs = 100)

Epoch 1/100
1/1 [==============================] - 0s 206ms/step - loss: 0.6365
Epoch 2/100
1/1 [==============================] - 0s 10ms/step - loss: 0.6365
Epoch 3/100
1/1 [==============================] - 0s 9ms/step - loss: 0.6365
Epoch 4/100
1/1 [==============================] - 0s 7ms/step - loss: 0.6365
Epoch 5/100
1/1 [==============================] - 0s 10ms/step - loss: 0.6365
Epoch 6/100
1/1 [==============================] - 0s 8ms/step - loss: 0.6365
Epoch 7/100
1/1 [==============================] - 0s 10ms/step - loss: 0.6365
Epoch 8/100
1/1 [==============================] - 0s 8ms/step - loss: 0.6365
Epoch 9/100
1/1 [==============================] - 0s 9ms/step - loss: 0.6365
Epoch 10/100
1/1 [==============================] - 0s 9ms/step - loss: 0.6365
Epoch 11/100
1/1 [==============================] - 0s 11ms/step - loss: 0.6365
Epoch 12/100
1/1 [==============================] - 0s 9ms/step - loss: 0.6365
Epoch 13/100
1/1 [==============================] - 0s 

In [36]:
x_new = [[340.0, 40.0]]

In [37]:
model.predict(x_new)

1/1 [==============================] - 0s 24ms/step


array([[0.66686505]], dtype=float32)