# Binary Classification - Neural Network

In [6]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

## DataSet

In [7]:
path = "dataset-01/iris/"
dataSet = pd.read_csv(path+'iris.csv')
dataSet = dataSet[:100] # Only 2 classes: Iris-setosa and Iris-versicolor
#print(dataSet)
# Shuffling dataframe
data = dataSet.sample(frac=1).reset_index(drop=True)

data[20:40]

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
20,76,6.6,3.0,4.4,1.4,Iris-versicolor
21,12,4.8,3.4,1.6,0.2,Iris-setosa
22,51,7.0,3.2,4.7,1.4,Iris-versicolor
23,68,5.8,2.7,4.1,1.0,Iris-versicolor
24,27,5.0,3.4,1.6,0.4,Iris-setosa
25,17,5.4,3.9,1.3,0.4,Iris-setosa
26,16,5.7,4.4,1.5,0.4,Iris-setosa
27,66,6.7,3.1,4.4,1.4,Iris-versicolor
28,50,5.0,3.3,1.4,0.2,Iris-setosa
29,77,6.8,2.8,4.8,1.4,Iris-versicolor


In [8]:
data["Species"] = data["Species"].apply(lambda x: x.replace("Iris-setosa", "0"))
data["Species"] = data["Species"].apply(lambda x: x.replace("Iris-versicolor", "1"))
data = data.astype(float)
data[:20]

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,52.0,6.4,3.2,4.5,1.5,1.0
1,79.0,6.0,2.9,4.5,1.5,1.0
2,42.0,4.5,2.3,1.3,0.3,0.0
3,80.0,5.7,2.6,3.5,1.0,1.0
4,91.0,5.5,2.6,4.4,1.2,1.0
5,32.0,5.4,3.4,1.5,0.4,0.0
6,74.0,6.1,2.8,4.7,1.2,1.0
7,56.0,5.7,2.8,4.5,1.3,1.0
8,37.0,5.5,3.5,1.3,0.2,0.0
9,48.0,4.6,3.2,1.4,0.2,0.0


In [9]:
X = data.iloc[ : , 1:5 ].values
y = data.iloc[ : , 5:6 ].values
y = y.astype(int)

In [10]:
print(X[:5])
print(y[:5])
print(np.shape(X))
print(np.shape(y))



[[6.4 3.2 4.5 1.5]
 [6.  2.9 4.5 1.5]
 [4.5 2.3 1.3 0.3]
 [5.7 2.6 3.5 1. ]
 [5.5 2.6 4.4 1.2]]
[[1]
 [1]
 [0]
 [1]
 [1]]
(100, 4)
(100, 1)


# Dataset split

In [11]:
from sklearn.model_selection import train_test_split
import tensorflow as tf

In [12]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state=10)

In [13]:
print(len(X_test))

20


## Tensorflow Model

### Model

In [14]:
model = Sequential([
    Dense(4, activation = 'relu', name = 'layer1'),
    Dense(1, activation = 'sigmoid', name = 'layers2')
])

In [15]:
model.compile(
    loss = tf.keras.losses.BinaryCrossentropy(),
    optimizer = tf.keras.optimizers.Adam(0.01)
)

In [16]:
model.fit(
    X_train, y_train,
    epochs= 100
)

Epoch 1/100
3/3 [==============================] - 2s 4ms/step - loss: 0.7872
Epoch 2/100
3/3 [==============================] - 0s 7ms/step - loss: 0.6788
Epoch 3/100
3/3 [==============================] - 0s 5ms/step - loss: 0.6312
Epoch 4/100
3/3 [==============================] - 0s 4ms/step - loss: 0.6194
Epoch 5/100
3/3 [==============================] - 0s 2ms/step - loss: 0.6149
Epoch 6/100
3/3 [==============================] - 0s 3ms/step - loss: 0.6044
Epoch 7/100
3/3 [==============================] - 0s 4ms/step - loss: 0.5898
Epoch 8/100
3/3 [==============================] - 0s 3ms/step - loss: 0.5718
Epoch 9/100
3/3 [==============================] - 0s 4ms/step - loss: 0.5530
Epoch 10/100
3/3 [==============================] - 0s 4ms/step - loss: 0.5312
Epoch 11/100
3/3 [==============================] - 0s 3ms/step - loss: 0.5085
Epoch 12/100
3/3 [==============================] - 0s 3ms/step - loss: 0.4855
Epoch 13/100
3/3 [==============================] - 0s 3ms/st

The `model.summary()` provides a description of the network:

In [17]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 layer1 (Dense)              (None, 4)                 20        
                                                                 
 layers2 (Dense)             (None, 1)                 5         
                                                                 
Total params: 25
Trainable params: 25
Non-trainable params: 0
_________________________________________________________________



4 4 5
O|O|O
O|O|
O|O|
O|O|

LAYERS1
4X4+4 = 20

LAYERS 2
4+1=5
))


The parameter counts shown in the summary correspond to the number of elements in the weight and bias arrays as shown below.

### Performance Analysis

In [22]:
prediction = model.predict(X_test)

1/1 [==============================] - 0s 18ms/step


In [24]:
binaryPred = (prediction > 0.5).astype(int)

for i in range(len(y_test)):
    print(f"Actual: {y_test[i]} - Prediction: {binaryPred[i]}")

Actual: [0] - Prediction: [0]
Actual: [1] - Prediction: [1]
Actual: [0] - Prediction: [0]
Actual: [0] - Prediction: [0]
Actual: [1] - Prediction: [1]
Actual: [1] - Prediction: [1]
Actual: [0] - Prediction: [0]
Actual: [0] - Prediction: [0]
Actual: [1] - Prediction: [1]
Actual: [0] - Prediction: [0]
Actual: [0] - Prediction: [0]
Actual: [1] - Prediction: [1]
Actual: [0] - Prediction: [0]
Actual: [1] - Prediction: [1]
Actual: [0] - Prediction: [0]
Actual: [1] - Prediction: [1]
Actual: [1] - Prediction: [1]
Actual: [0] - Prediction: [0]
Actual: [0] - Prediction: [0]
Actual: [0] - Prediction: [0]


In [26]:
accuracy = tf.keras.metrics.CategoricalAccuracy()(y_test, prediction).numpy()
print(f"Accuracy: {accuracy*100:.2f}%")

Accuracy: 100.00%
