# Numpy


# Arrays

In [1]:
import numpy as np

In [2]:
array1 = np.array([1,2,3,8,7,6,5])
print(type(array1))
print(array1)

<class 'numpy.ndarray'>
[1 2 3 8 7 6 5]


In [5]:
array2 = np.array([[1,2,3],[8,7,6],[1,2,3]])
print(array2)

[[1 2 3]
 [8 7 6]
 [1 2 3]]


In [6]:
print(array2.shape)

(3, 3)


In [7]:
flattened = array2.flatten()
print(flattened)

[1 2 3 8 7 6 1 2 3]


In [8]:
array2.T

array([[1, 8, 1],
       [2, 7, 2],
       [3, 6, 3]])

In [15]:
array2.reshape(1,9)

array([[1, 2, 3, 8, 7, 6, 1, 2, 3]])

In [16]:
array2.reshape(3,3)

array([[1, 2, 3],
       [8, 7, 6],
       [1, 2, 3]])

In [17]:
array3 = array2.reshape(3,3)

In [21]:
print(array3[0:3,0])

[1 8 1]


In [24]:
tmpZeros = np.zeros(array3.shape)
tmpZeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [25]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [27]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [28]:
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[6,7],[8,9]])

In [29]:
print(arr1 + arr2)

[[ 7  9]
 [11 13]]


In [30]:
print(arr1 * arr2)

[[ 6 14]
 [24 36]]


In [31]:
print(arr2*2)

[[12 14]
 [16 18]]


In [32]:
print(np.dot(arr1, arr2))

[[22 25]
 [50 57]]


In [40]:
arr3 = np.append(arr1,arr2)
arr3

array([1, 2, 3, 4, 6, 7, 8, 9])

In [41]:
arr3 = np.append(arr1,arr2,axis=0)
arr3

array([[1, 2],
       [3, 4],
       [6, 7],
       [8, 9]])

In [42]:
arr3 = np.append(arr1,arr2,axis=1)
arr3

array([[1, 2, 6, 7],
       [3, 4, 8, 9]])

# Vectorization vs Loop

In [8]:
# Using a Python list
lst = [1, 2, 3, 4, 5]
new_list = [x * 2 for x in lst]
print('List:', new_list)

# Using a NumPy array
arr = np.array([1, 2, 3, 4, 5])  # Now np is defined
new_arr = arr * 2
print('Array:', new_arr)

List: [2, 4, 6, 8, 10]
Array: [ 2  4  6  8 10]


In [7]:
import numpy as np
import time

# Create test data
size = 10**7  # 10 million elements
lst = list(range(size))
arr = np.arange(size)  # Fixed: changed arrange to arange

# Time list operation
start = time.time()
lst_result = [x * 2 for x in lst]
time_lst = time.time() - start

# Time NumPy array operation
start = time.time()
arr_result = arr * 2
time_arr = time.time() - start

print('Time with list:', time_lst)
print('Time with NumPy array:', time_arr)



Time with list: 0.5711116790771484
Time with NumPy array: 0.013124465942382812
